apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: php-fpm
  name: php-fpm
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: php-fpm
    spec:
      containers:
      - image: decyt/larasiep-fpm:0.0.5
        name: laravel-api-php
        resources: {}
        workingDir: /application
      restartPolicy: Always
status: {}
