apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - image: decyt/weblarasiep:0.0.1
        name: laravel-api-web
        ports:
        - containerPort: 80
        resources: {}
        command: ["/bin/sh"]
        args: ["-c", "envsubst '$UPSTREAM' < /etc/nginx/conf.d/nginx.tpl > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
        env:
        - name: UPSTREAM
          value: php-fpm:9000
        workingDir: /application
      restartPolicy: Always
status: {}
